name: Neon DB Integration

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  neon-db-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Connect to Neon database and run script
        env:
          DATABASE_URL: postgresql://neondb_owner:npg_yMXmTz81aPCD@ep-polished-waterfall-a5szq7p4-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
        run: |
          node your-script-that-connects-to-neon.js
